name: Check

on: [push, pull_request]

jobs:
  black:
    name: Python black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make qa-black

  flake8:
    name: Python flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make qa-flake8

  pytest:
    name: Python pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make qa-pytest
