name: Check and Build

on: [push, pull_request]

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make qa-codespell

  pytest:
    name: Python Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make qa-pytest

  ruff:
    name: Python Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make qa-ruff

  build:
    name: Python Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # include tags and full history for setuptools_scm
          fetch-depth: 0
      - run: make build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
